export const EVIDENCE_CONFIG = {
  WEIGHTS: {
    INDEPENDENT_PUBLISHER: 0.25,
    PRIMARY_SOURCE: 0.20,
    SOURCE_DIVERSITY: 0.20,
    FRESHNESS: 0.15,
    AUTHORITY: 0.10,
    AGREEMENT: 0.10,
  },

  INDEPENDENT_PUBLISHER_SCALING: {
    ONE: 30,
    TWO: 60,
    THREE: 85,
    FOUR_OR_MORE: 100,
  },

  PRIMARY_SOURCE_SCALING: {
    ZERO: 0,
    ONE: 80,
    TWO_OR_MORE: 100,
  },

  SOURCE_DIVERSITY_SCALING: {
    ONE_TYPE: 30,
    TWO_TYPES: 65,
    THREE_OR_MORE_TYPES: 100,
  },

  AUTHORITY_SCALING: {
    TIER_1: 100,
    TIER_2: 70,
    TIER_3: 40,
  },

  AGREEMENT_SCALING: {
    NO_CONFLICTS: 100,
    LOW_SEVERITY_CONFLICT: 75,
    MEDIUM_SEVERITY_CONFLICT: 45,
    HIGH_SEVERITY_CONFLICT: 15,
  },

  CONFIDENCE_THRESHOLDS: {
    WELL_SUPPORTED_MIN_SCORE: 70,
    WELL_SUPPORTED_MIN_INDEPENDENT: 3,
    WELL_SUPPORTED_WITH_PRIMARY_MIN_INDEPENDENT: 2,
    DEVELOPING_MIN_INDEPENDENT: 2,
    LIMITED_INDEPENDENT: 1,
  },
} as const;
